### ISSUE TITLE
Rename ProtobufOperationAttribute to ProtobufMethodAttribute

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3741]
In Protobuf, operations are typically referred to as 'methods'. Therefore, it might be logical to use `ProtobufMethodAttribute` as the attribute name

**Comment by bernardnormier** [comment]
I agree.

`ProtobufOperationAttribute` is not incorrect since it's about specifying the operation in the icerpc / ice request header. 

However, this operation must be the Protobuf rpc method name - that's an essential part of the Protobuf contract. And if you're using Protobuf as your IDL, you should be insulated from low-level details like the exact names used in icerpc request headers.
