### ISSUE TITLE
Missing idempotency check in Protobuf-generated code

### ISSUE THREAD

**Issue by pepone** [icerpc/icerpc-csharp#3757]
The code generated by Slice calls [`CheckNonIdempotent`](https://github.com/icerpc/icerpc-csharp/blob/fbd611d007b8cadfc995e1474885262307decd1b/src/IceRpc.Slice/IncomingRequestExtensions.cs#L19-L26) to ensure that operations not marked as idempotent do not accept idempotent requests.

However, the code generated by Protobuf lacks a similar check.

This issue was identified during the review of the idempotent test for Protobuf, as seen here: [Protobuf idempotent test review](https://github.com/icerpc/icerpc-csharp/pull/3753#issuecomment-1812849443).

**Comment by pepone** [comment]
Should we add a similar check for Protobuf?

**Comment by bernardnormier** [comment]
In my view, options in Protobuf are comparable to attributes in Slice - not part of the contract. The options of your client and server can be out of sync and that's fine.

In Protobuf, you specify this idempotentness with an option (idempotency_level) in your client-side Protobuf and (unless I am missing something) the server-side Protobof doesn't need a matching option. With gRPC, it presumably affects the verb (GET / PUT / POST)  of the HTTP request sent by the client.

Contrast this with Slice, where idempotent is a keyword, because:
 a) IceRPC (and Ice) request carry an idempotent field
 b) we check in the server-side generated code the client and server side definitions are compatible

So no, I wouldn't add this check with Protobuf.
